# How to use:
# Simply type 'make'
# Then move the created libftprintf.a
NAME = libft.a
#LIBFT = ../libft/libft.a
all:
	gcc -Wall -Wextra -Werror -Wno-unused-result -c *.c
	ar rcs $(NAME) *.o
clean:
	rm -f *.o
fclean: clean
	rm -f $(NAME)
re: fclean all./a.

.PHONY: all clean fclean re 	 	
